# version: '3.8'
# services:
#   api:
#     container_name: api
#     restart: always
#     build: .
#     ports:
#       - ${PORT}:${PORT}
#     depends_on:
#       - db
#     volumes:
#     - .:/usr/src/app

#   db:
#     container_name: postgres
#     image: postgres
#     ports:
#       - '5433:${DB_PORT}'
#     volumes:
#       - data:/data/db
#     environment:
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=${DB_NAME}

# volumes: 
#  data: {}

version: '3.8'
services:
  db:
    image: postgres
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres-data:
